using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using NUnit.Framework;
using UnityEngine;

namespace BitSorter.LogicCore.Tests
{
    /// <summary>
    /// The saved scene, read as a file: that every reference the builder was supposed to wire
    /// actually survived serialisation.
    /// </summary>
    /// <remarks>
    /// The trap CLAUDE.md has warned about from the beginning, and the only test that can see it.
    /// `HalfAdderDemoSceneBuilder` is the sole authority on scene contents, and a reference can
    /// serialise as `{fileID: 0}` while the setup code that assigned it looks perfectly correct. The
    /// scene then opens fine on the machine that built it and is broken for a fresh clone.
    ///
    /// **It has to read the file.** The obvious version -- load the scene in Play Mode and reflect
    /// over the fields -- cannot work, because every component in this project ends Awake with
    /// `if (_x == null) _x = FindFirstObjectByType&lt;X&gt;()`. The fallback fills in whatever the
    /// builder missed before any test can look, so a field that serialised as null is
    /// indistinguishable from one that serialised correctly. `SceneCompositionPlayTests` checks the
    /// runtime half and says so in its own name; this checks the half that only exists on disk.
    ///
    /// Reading YAML with a regular expression is usually a bad idea. It is fine here because the
    /// shape being matched is one line of Unity's own generated output, the file is regenerated by a
    /// menu item rather than hand-edited, and the alternative is a YAML dependency for one test.
    /// </remarks>
    public class SceneWiringTests
    {
        private const string ScenePath = "Scenes/HalfAdderDemo.unity";

        /// <summary>
        /// Object references Unity writes for its own bookkeeping, which are legitimately zero.
        /// </summary>
        /// <remarks>
        /// `m_CorrespondingSourceObject` and the two prefab fields are zero on every component that
        /// is not a prefab instance, which is all of them here. `m_Script` and `m_GameObject` are
        /// never zero but are Unity's to answer for, not the builder's.
        /// </remarks>
        private static readonly HashSet<string> UnitysOwn = new HashSet<string>
        {
            "m_CorrespondingSourceObject", "m_PrefabInstance", "m_PrefabAsset",
            "m_GameObject", "m_Script",
        };

        private static readonly Regex ClassIdentifier =
            new Regex(@"m_EditorClassIdentifier:\s*(\S+)", RegexOptions.Compiled);

        /// <summary>A field holding an object reference, at the indentation Unity writes them.</summary>
        private static readonly Regex ObjectField =
            new Regex(@"^  (\w+): \{fileID: (-?\d+)", RegexOptions.Multiline | RegexOptions.Compiled);

        private readonly struct Reference
        {
            public readonly string Component;
            public readonly string Field;
            public readonly bool Wired;

            public Reference(string component, string field, bool wired)
            {
                Component = component;
                Field = field;
                Wired = wired;
            }

            public override string ToString() => Component + "." + Field;
        }

        private static string SceneText()
        {
            string path = Path.Combine(Application.dataPath, ScenePath);

            Assert.IsTrue(File.Exists(path), "no scene at " + path);

            return File.ReadAllText(path);
        }

        /// <summary>Every object reference on every BitSorter component in the saved scene.</summary>
        private static List<Reference> ReferencesInScene()
        {
            var found = new List<Reference>();

            // Unity writes one YAML document per object, each introduced by this marker.
            foreach (string document in SceneText().Split(new[] { "--- !u!" }, System.StringSplitOptions.None))
            {
                if (!document.Contains("MonoBehaviour:"))
                    continue;

                Match identifier = ClassIdentifier.Match(document);

                if (!identifier.Success)
                    continue;

                // "BitSorter.View::BitSorter.View.GameAudio" -- the assembly, then the full name.
                string identity = identifier.Groups[1].Value;

                if (!identity.Contains("BitSorter"))
                    continue;

                string component = identity.Substring(identity.LastIndexOf('.') + 1);

                foreach (Match field in ObjectField.Matches(document))
                {
                    string name = field.Groups[1].Value;

                    if (UnitysOwn.Contains(name))
                        continue;

                    found.Add(new Reference(component, name, field.Groups[2].Value != "0"));
                }
            }

            return found;
        }

        /// <summary>
        /// The scene really was read, and really does contain the game.
        /// </summary>
        /// <remarks>
        /// The test below is an assertion about absence: it passes trivially if the parse found
        /// nothing, which is exactly how a green test can prove nothing at all. A regex that stopped
        /// matching after a Unity upgrade changed the serialisation format would fail silently and
        /// look like success.
        ///
        /// The numbers are floors rather than exact counts, so adding a component does not fail this
        /// -- but losing most of them does.
        /// </remarks>
        [Test]
        public void TheSceneWasActuallyParsed()
        {
            List<Reference> references = ReferencesInScene();

            Assert.Greater(references.Count, 60,
                "the scene parse found almost no object references, so the wiring check below is " +
                "vacuous -- most likely Unity's serialisation format changed");

            var components = new HashSet<string>();

            foreach (Reference reference in references)
                components.Add(reference.Component);

            Assert.Greater(components.Count, 20,
                "far fewer BitSorter components in the scene than the builder adds");

            // A few the game cannot run without, named so a silent parse failure cannot pass.
            foreach (string expected in new[] { "LevelSession", "SimulationRunner", "ProgressTracker" })
            {
                CollectionAssert.Contains(components, expected,
                    expected + " is missing from the saved scene");
            }
        }

        [Test]
        public void EveryReferenceInTheSavedScene_IsWired()
        {
            var empty = new List<string>();

            foreach (Reference reference in ReferencesInScene())
            {
                if (!reference.Wired)
                    empty.Add(reference.ToString());
            }

            CollectionAssert.IsEmpty(empty,
                "serialised as {fileID: 0} in HalfAdderDemo.unity, so the scene builder did not " +
                "wire them and only the Awake fallback is hiding it:\n  " + string.Join("\n  ", empty)
                + "\nRebuild with BitSorter/Build Play Scene, then check the assignment.");
        }

        /// <summary>
        /// The parser can tell a wired reference from an empty one.
        /// </summary>
        /// <remarks>
        /// The same reasoning as the corpus check above, one level down: the test that matters says
        /// "nothing is zero", and that is worthless unless something proves zero would be noticed.
        /// This is the exact text Unity writes in both cases.
        /// </remarks>
        [Test]
        public void TheParserNoticesAnEmptyReference()
        {
            const string wired = "^  _session: {fileID: 794885924}";
            const string missing = "^  _session: {fileID: 0}";

            Match good = ObjectField.Match(wired.Substring(1));
            Match bad = ObjectField.Match(missing.Substring(1));

            Assert.IsTrue(good.Success, "the parser no longer recognises a wired reference");
            Assert.AreNotEqual("0", good.Groups[2].Value);

            Assert.IsTrue(bad.Success, "the parser no longer recognises an empty reference");
            Assert.AreEqual("0", bad.Groups[2].Value,
                "an empty reference must be seen as empty, or the whole test is decorative");
        }
    }
}
