using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.UI;
using TMPro;

namespace BitSorter.View
{
    /// <summary>
    /// The front door: a title, where you left off, and the way back to it.
    /// </summary>
    /// <remarks>
    /// An overlay in the same scene rather than a separate one, for the same reason level select is:
    /// the play scene is generated by the scene builder, so a second scene would be a second thing to
    /// construct and keep in step, and the session already switches level at runtime.
    ///
    /// Shown at startup. Until something is chosen the board is covered, and <see cref="UiModal"/>
    /// keeps the keyboard quiet as well -- otherwise Q behind the menu would change level under it.
    /// </remarks>
    public sealed class MainMenu : MonoBehaviour
    {
        [SerializeField] private LevelSession _session;
        [SerializeField] private ProgressTracker _progress;
        [SerializeField] private LevelSelectPanel _levels;
        [SerializeField] private SandboxPanel _sandbox;

        [Tooltip("Canvas the menu is built under. Found by type when left empty.")]
        [SerializeField] private Canvas _canvas;

        [Tooltip("Open the menu on startup. Off is useful when working on a level.")]
        [SerializeField] private bool _openOnStart = true;

        private RectTransform _root;
        private TextMeshProUGUI _progressLine;
        private TextMeshProUGUI _continueLabel;
        private TextMeshProUGUI _soundLabel;
        private TextMeshProUGUI _dataLabel;
        private TextMeshProUGUI _nextLine;
        private GameAudio _audio;
        private bool _shown;

        /// <summary>
        /// Held rather than built per call: <see cref="Refresh"/> runs every frame the menu is up, and
        /// a fresh closure each time would be per-frame garbage for a screen that is standing still.
        /// </summary>
        private Predicate<string> _isComplete;

        /// <summary>Whether the menu is covering the board.</summary>
        public bool IsOpen => _shown;

        private void Awake()
        {
            if (_session == null) _session = FindFirstObjectByType<LevelSession>();
            if (_progress == null) _progress = FindFirstObjectByType<ProgressTracker>();
            if (_levels == null) _levels = FindFirstObjectByType<LevelSelectPanel>();
            if (_sandbox == null) _sandbox = FindFirstObjectByType<SandboxPanel>();
            if (_audio == null) _audio = FindFirstObjectByType<GameAudio>();
            if (_canvas == null) _canvas = FindFirstObjectByType<Canvas>();
        }

        private void Start()
        {
            if (_canvas == null)
                return;

            Build();
            Show(_openOnStart);
        }

        private void OnDisable() => UiModal.Closed(this);

        private void Update()
        {
            Keyboard keyboard = Keyboard.current;

            // M, not Escape. Escape belongs to level select, and a key that closed one panel and
            // opened another depending on what was showing would be unpredictable.
            //
            // Closes whatever else is open, but only opens when nothing is -- otherwise M behind the
            // level list stacked the menu under it, which is how this read in play: two full-screen
            // panels at once, one of them unreachable.
            if (keyboard != null && keyboard.mKey.wasPressedThisFrame
                && (_shown || !UiModal.AnyOpen))
            {
                Show(!_shown);
            }

            if (_shown)
                Refresh();
        }

        // -----------------------------------------------------------------
        // Building
        // -----------------------------------------------------------------

        private void Build()
        {
            Image scrim = UiTheme.Panel_("Main menu", _canvas.transform, new Color(0f, 0f, 0f, 0.88f));
            _root = scrim.GetComponent<RectTransform>();
            UiTheme.Stretch(_root);

            TextMeshProUGUI title = UiTheme.Label(
                "title", _root, 54f, UiTheme.Accent, TextAlignmentOptions.Center);
            UiTheme.Anchor(title.rectTransform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, 150f), new Vector2(700f, 70f));
            title.text = "BITSORTER";

            TextMeshProUGUI tagline = UiTheme.Label(
                "tagline", _root, 18f, UiTheme.TextDim, TextAlignmentOptions.Center);
            UiTheme.Anchor(tagline.rectTransform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, 104f), new Vector2(700f, 26f));
            tagline.text = "bits fall through logic. sort them.";

            // A rule under the title. The menu was a title and three buttons floating in black,
            // which reads as unfinished rather than as spare.
            Image rule = UiTheme.Panel_("rule", _root, UiTheme.Accent * 0.4f);
            UiTheme.Anchor(rule.GetComponent<RectTransform>(),
                new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, 78f), new Vector2(320f, 2f));

            Button resume = Item("Continue", 32f, out _continueLabel);
            resume.onClick.AddListener(() => Fire(Continue));

            Button levels = Item("Levels", -22f, out TextMeshProUGUI _);
            levels.onClick.AddListener(() => Fire(OpenLevels));

            // Below the run, not beside it. Free play is where someone goes once the levels have
            // taught them something, and putting it first would offer a blank board to a player who
            // has not yet been told what a board is for.
            Button sandbox = Item("Sandbox", -76f, out TextMeshProUGUI _);
            sandbox.onClick.AddListener(() => Fire(OpenSandbox));

            Button sound = Item("Sound", -130f, out _soundLabel);
            sound.onClick.AddListener(() => Fire(ToggleSound));

            // The off switch for reporting. In the menu rather than buried, because a setting nobody
            // can find is not a choice -- and the README tells players it is here.
            Button data = Item("Data", -184f, out _dataLabel);
            data.onClick.AddListener(() => Fire(ToggleData));

            // No Quit in a browser. Application.Quit does nothing there -- a tab is closed by the
            // browser, not by the page -- so the button would sit in the menu doing nothing at all,
            // which is worse than not offering it.
#if !UNITY_WEBGL || UNITY_EDITOR
            Button quit = Item("Quit", -238f, out TextMeshProUGUI _);
            quit.onClick.AddListener(() => Fire(Quit));
#endif

            // Where Continue actually goes. "CONTINUE" alone tells a returning player nothing about
            // which of nine levels they are about to land on.
            // These follow the bottom of the button column, which has grown twice -- once for Sandbox
            // and once for Data. The canvas is 1080 tall, so there is room below -238 for both.
            _nextLine = UiTheme.Label(
                "next", _root, 15f, UiTheme.Accent, TextAlignmentOptions.Center);
            UiTheme.Anchor(_nextLine.rectTransform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, -286f), new Vector2(700f, 22f));

            _progressLine = UiTheme.Label(
                "progress", _root, 16f, UiTheme.TextDim, TextAlignmentOptions.Center);
            UiTheme.Anchor(_progressLine.rectTransform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, -312f), new Vector2(700f, 24f));

            TextMeshProUGUI keys = UiTheme.Label(
                "keys", _root, 13f, UiTheme.TextDim, TextAlignmentOptions.Center);
            UiTheme.Anchor(keys.rectTransform, new Vector2(0.5f, 0f), new Vector2(0.5f, 0f),
                new Vector2(0f, 30f), new Vector2(900f, 20f));
            keys.text = "M menu     ESC levels     H help     N mute";
        }

        private Button Item(string name, float y, out TextMeshProUGUI label)
        {
            Button button = UiTheme.Button_(name, _root, name.ToUpperInvariant(), out label);

            UiTheme.Anchor(button.GetComponent<RectTransform>(),
                new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, y), new Vector2(240f, UiTheme.ButtonHeight + 6f));

            return button;
        }

        // -----------------------------------------------------------------
        // Contents
        // -----------------------------------------------------------------

        private void Refresh()
        {
            if (_session == null || !_session.IsLoaded)
                return;

            int total = _session.Catalogue.Count;
            int done = SolvedCount();

            _progressLine.text = MenuRules.DescribeProgress(done, total);

            // "Continue" on a fresh save is a lie -- there is nothing to continue from.
            bool fresh = done == 0 && _session.LevelIndex == 0;

            _continueLabel.text = fresh ? "START" : "CONTINUE";
            _soundLabel.text = GameAudio.MusicMuted ? "SOUND  OFF" : "SOUND  ON";
            _dataLabel.text = GameAnalytics.Reporting ? "DATA  ON" : "DATA  OFF";

            // Named from the same walk Continue itself uses, so the label cannot promise one level
            // and the button open another. Asked only once the run is known to have a frontier left:
            // an empty catalogue has no next level, and used to throw here rather than say so.
            if (MenuRules.AllSolved(done, total))
                _nextLine.text = "all solved -- replay anything you like";
            else if (TryNextUp(out LevelEntry next))
                _nextLine.text = $"next up: {next.DisplayName}";
            else
                _nextLine.text = string.Empty;
        }

        /// <summary>The level <see cref="Continue"/> would open, if the run has one.</summary>
        private bool TryNextUp(out LevelEntry next) =>
            MenuRules.TryNextUp(_session.Catalogue, IsComplete, out next);

        private Predicate<string> IsComplete =>
            _isComplete ?? (_isComplete = name => _progress != null && _progress.IsComplete(name));

        private void ToggleSound()
        {
            if (_audio != null)
                _audio.ToggleMusic();

            Refresh();
        }

        private void ToggleData()
        {
            GameAnalytics.SetReporting(!GameAnalytics.Reporting);
            Refresh();
        }

        private int SolvedCount()
        {
            if (_progress == null)
                return 0;

            int done = 0;

            foreach (LevelEntry entry in _session.Catalogue)
            {
                if (_progress.IsComplete(entry.FileName))
                    done++;
            }

            return done;
        }

        // -----------------------------------------------------------------
        // Choices
        // -----------------------------------------------------------------

        /// <summary>
        /// Closes the menu onto the first level not yet solved.
        /// </summary>
        /// <remarks>
        /// Furthest unsolved rather than last played, because the two differ exactly when it matters:
        /// a player who wandered into a late level from the list and closed the game should come back
        /// to the run, not to wherever they were browsing. Everything solved means the last level, so
        /// the button always goes somewhere.
        /// </remarks>
        private void Continue()
        {
            Show(false);

            if (_session == null || !_session.IsLoaded)
                return;

            // The empty-catalogue guard lives in the walk now, so both callers get it.
            if (!TryNextUp(out LevelEntry next))
                return;

            if (next.FileName != _session.LevelName)
                _session.LoadLevel(next.FileName);
        }

        private void OpenLevels()
        {
            Show(false);

            if (_levels != null)
                _levels.Open();
        }

        private void OpenSandbox()
        {
            Show(false);

            if (_sandbox != null)
                _sandbox.Open();
        }

#if !UNITY_WEBGL || UNITY_EDITOR
        private static void Quit()
        {
#if UNITY_EDITOR
            // Application.Quit does nothing in the editor, so a Quit button that appeared to be
            // broken is worse than one that leaves play mode.
            UnityEditor.EditorApplication.isPlaying = false;
#else
            Application.Quit();
#endif
        }
#endif

        // -----------------------------------------------------------------
        // Showing
        // -----------------------------------------------------------------

        public void Show(bool visible)
        {
            _shown = visible;

            if (_root != null && _root.gameObject.activeSelf != visible)
                _root.gameObject.SetActive(visible);

            if (visible)
            {
                UiTheme.BringToFront(_root);
                UiModal.Opened(this);
                Refresh();
            }
            else
            {
                UiModal.Closed(this);
            }
        }

        private void Fire(System.Action action)
        {
            action();

            if (EventSystem.current != null)
                EventSystem.current.SetSelectedGameObject(null);
        }
    }
}
