using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.UI;
using TMPro;

namespace BitSorter.View
{
    /// <summary>
    /// The front door: a title, where you left off, and the way back to it.
    /// </summary>
    /// <remarks>
    /// An overlay in the same scene rather than a separate one, for the same reason level select is:
    /// the play scene is generated by the scene builder, so a second scene would be a second thing to
    /// construct and keep in step, and the session already switches level at runtime.
    ///
    /// Shown at startup. Until something is chosen the board is covered, and <see cref="UiModal"/>
    /// keeps the keyboard quiet as well -- otherwise Q behind the menu would change level under it.
    /// </remarks>
    public sealed class MainMenu : MonoBehaviour
    {
        [SerializeField] private LevelSession _session;
        [SerializeField] private ProgressTracker _progress;
        [SerializeField] private LevelSelectPanel _levels;

        [Tooltip("Canvas the menu is built under. Found by type when left empty.")]
        [SerializeField] private Canvas _canvas;

        [Tooltip("Open the menu on startup. Off is useful when working on a level.")]
        [SerializeField] private bool _openOnStart = true;

        private RectTransform _root;
        private TextMeshProUGUI _progressLine;
        private TextMeshProUGUI _continueLabel;
        private bool _shown;

        /// <summary>Whether the menu is covering the board.</summary>
        public bool IsOpen => _shown;

        private void Awake()
        {
            if (_session == null) _session = FindFirstObjectByType<LevelSession>();
            if (_progress == null) _progress = FindFirstObjectByType<ProgressTracker>();
            if (_levels == null) _levels = FindFirstObjectByType<LevelSelectPanel>();
            if (_canvas == null) _canvas = FindFirstObjectByType<Canvas>();
        }

        private void Start()
        {
            if (_canvas == null)
                return;

            Build();
            Show(_openOnStart);
        }

        private void OnDisable() => UiModal.Closed(this);

        private void Update()
        {
            Keyboard keyboard = Keyboard.current;

            // M, not Escape. Escape belongs to level select, and a key that closed one panel and
            // opened another depending on what was showing would be unpredictable.
            //
            // Closes whatever else is open, but only opens when nothing is -- otherwise M behind the
            // level list stacked the menu under it, which is how this read in play: two full-screen
            // panels at once, one of them unreachable.
            if (keyboard != null && keyboard.mKey.wasPressedThisFrame
                && (_shown || !UiModal.AnyOpen))
            {
                Show(!_shown);
            }

            if (_shown)
                Refresh();
        }

        // -----------------------------------------------------------------
        // Building
        // -----------------------------------------------------------------

        private void Build()
        {
            Image scrim = UiTheme.Panel_("Main menu", _canvas.transform, new Color(0f, 0f, 0f, 0.88f));
            _root = scrim.GetComponent<RectTransform>();
            UiTheme.Stretch(_root);

            TextMeshProUGUI title = UiTheme.Label(
                "title", _root, 54f, UiTheme.Accent, TextAlignmentOptions.Center);
            UiTheme.Anchor(title.rectTransform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, 150f), new Vector2(700f, 70f));
            title.text = "BITSORTER";

            TextMeshProUGUI tagline = UiTheme.Label(
                "tagline", _root, 18f, UiTheme.TextDim, TextAlignmentOptions.Center);
            UiTheme.Anchor(tagline.rectTransform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, 104f), new Vector2(700f, 26f));
            tagline.text = "bits fall through logic. sort them.";

            Button resume = Item("Continue", 30f, out _continueLabel);
            resume.onClick.AddListener(() => Fire(Continue));

            Button levels = Item("Levels", -30f, out TextMeshProUGUI _);
            levels.onClick.AddListener(() => Fire(OpenLevels));

            Button quit = Item("Quit", -90f, out TextMeshProUGUI _);
            quit.onClick.AddListener(() => Fire(Quit));

            _progressLine = UiTheme.Label(
                "progress", _root, 16f, UiTheme.TextDim, TextAlignmentOptions.Center);
            UiTheme.Anchor(_progressLine.rectTransform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, -152f), new Vector2(700f, 24f));
        }

        private Button Item(string name, float y, out TextMeshProUGUI label)
        {
            Button button = UiTheme.Button_(name, _root, name.ToUpperInvariant(), out label);

            UiTheme.Anchor(button.GetComponent<RectTransform>(),
                new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f),
                new Vector2(0f, y), new Vector2(240f, UiTheme.ButtonHeight + 6f));

            return button;
        }

        // -----------------------------------------------------------------
        // Contents
        // -----------------------------------------------------------------

        private void Refresh()
        {
            if (_session == null || !_session.IsLoaded)
                return;

            int total = _session.Catalogue.Count;
            int done = SolvedCount();

            _progressLine.text = done == 0
                ? $"{total} levels"
                : $"{done} of {total} solved";

            // "Continue" on a fresh save is a lie -- there is nothing to continue from.
            _continueLabel.text = done == 0 && _session.LevelIndex == 0 ? "START" : "CONTINUE";
        }

        private int SolvedCount()
        {
            if (_progress == null)
                return 0;

            int done = 0;

            foreach (LevelEntry entry in _session.Catalogue)
            {
                if (_progress.IsComplete(entry.FileName))
                    done++;
            }

            return done;
        }

        // -----------------------------------------------------------------
        // Choices
        // -----------------------------------------------------------------

        /// <summary>
        /// Closes the menu onto the first level not yet solved.
        /// </summary>
        /// <remarks>
        /// Furthest unsolved rather than last played, because the two differ exactly when it matters:
        /// a player who wandered into a late level from the list and closed the game should come back
        /// to the run, not to wherever they were browsing. Everything solved means the last level, so
        /// the button always goes somewhere.
        /// </remarks>
        private void Continue()
        {
            Show(false);

            if (_session == null || !_session.IsLoaded || _progress == null)
                return;

            IReadOnlyList<LevelEntry> catalogue = _session.Catalogue;

            foreach (LevelEntry entry in catalogue)
            {
                if (!_progress.IsComplete(entry.FileName))
                {
                    if (entry.FileName != _session.LevelName)
                        _session.LoadLevel(entry.FileName);

                    return;
                }
            }

            if (catalogue.Count > 0)
                _session.LoadLevel(catalogue[catalogue.Count - 1].FileName);
        }

        private void OpenLevels()
        {
            Show(false);

            if (_levels != null)
                _levels.Open();
        }

        private static void Quit()
        {
#if UNITY_EDITOR
            // Application.Quit does nothing in the editor, so a Quit button that appeared to be
            // broken is worse than one that leaves play mode.
            UnityEditor.EditorApplication.isPlaying = false;
#else
            Application.Quit();
#endif
        }

        // -----------------------------------------------------------------
        // Showing
        // -----------------------------------------------------------------

        public void Show(bool visible)
        {
            _shown = visible;

            if (_root != null && _root.gameObject.activeSelf != visible)
                _root.gameObject.SetActive(visible);

            if (visible)
            {
                UiTheme.BringToFront(_root);
                UiModal.Opened(this);
                Refresh();
            }
            else
            {
                UiModal.Closed(this);
            }
        }

        private void Fire(System.Action action)
        {
            action();

            if (EventSystem.current != null)
                EventSystem.current.SetSelectedGameObject(null);
        }
    }
}
